---
abstract: 'Japanese phone number validation'
author:
  - 'Gosuke Miyashita <gosukenator@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FormValidator-Simple-Plugin-Number-Phone-JP
no_index:
  directory:
    - t
    - inc
requires:
  FormValidator::Simple: 0.03
  Number::Phone::JP: 0.03
version: 0.04
